name: 08 - Working with Inputs
run-name: ${{ github.workflow }}
on: 
    workflow_dispatch:
        inputs:          
            target:
                description: "Which environment the workflow will target"
                type: string
                default: dev
                
jobs:
    build:
        runs-on: self-hosted
        steps:
            - name: Build
              run: echo "Input Argument"


