name: 09 - Variables On Workflow
on: workflow_dispatch
env:
    message: Welcome
jobs:
    build:
        runs-on: ubuntu-latest
        env:
            first: ganesh
        steps:            
            - name: Displaying Variable
              run: echo "$message $first $last"
              env:
                last: moorthy

    test:
        runs-on: ubuntu-latest
        steps:
            - name: Display
              run: echo "$message $first"