name: 10 - Configuration Variables Repo Level
on: workflow_dispatch
jobs:
    build:
        runs-on: self-hosted
        steps:
            - name: Display Variable from Repo
              run: echo "Name is ${{ vars.name }}"

    test:
        runs-on: self-hosted
        steps:
            - name: Display Variable from Repo
              run: echo "Name is ${{ vars.name }}"

    deploy:
        runs-on: self-hosted
        steps:
            - name: Display Secret from Repo
              run: echo "Name is ${{ secrets.name }}"