name: 11 - Reusable Workflow
on: workflow_call
jobs:
    build:
        runs-on: self-hosted
        env:
            environment: dev  
        steps:
            - name: Build Job
              run: echo "This job is running on $environment"

    test:
        runs-on: self-hosted
        needs: build
        env:
            envi: test
        steps:
            - name: Build Job
              run: echo "This job is running on $envi"

    deploy:
        runs-on: self-hosted
        needs: [build, test]
        env:
            envir: prod
        steps:
            - name: Build Job
              run: echo "This job is running on $envir"

            
