name: 13 - Environments
on: 
  workflow_dispatch:
    inputs:
      environment:
        description: Choose which environment to deloy
        type: choice
        options:
          - dev
          - test
    
jobs:
    build:
        runs-on: self-hosted
        env:
          Environment: ${{ github.event.inputs.environment.dev }}
        steps:
            - name: Build on Dev
              run: | 
                echo "$Environment"
                echo "${{ vars.DEPLOYMENTNAME}}"                
        
    deploy:
        runs-on: self-hosted
        env:
          Environment: ${{ github.event.inputs.environment.test }}            
        steps:
          - name: Build on Test
            run: |
              echo "Running in $Environment"
              echo "${{ vars.DEPLOYMENTNAME}}"