name: 16 - Artifact Workflow
on: workflow_dispatch
jobs:
  build-job:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Create Directory & file
        run: |
            mkdir build
            cd build         
            echo "Artifact Data" > result.txt
            cat result.txt

      - name: Upload Artifact
        uses: actions/upload-artifact@v7
        with:
          name: my-artifact
          path: build/result.txt

  deploy-job:
    runs-on: self-hosted
    needs: build-job
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v8
        with:
          name: my-artifact
          path: deploy/result.txt
      - name: Verify
        run: |
            cd  deploy
            cat result.txt
