name: 17-Dynamic Variable
on: workflow_dispatch
jobs:
  dynamic_variable:
    runs-on: ubuntu-latest
    env:
      firstname: ganesh
      lastname: moorthy
    steps:
      - name: Settting Variable
        run: echo "FullName=$firstname-$lastname" >> $GITHUB_ENV

      - name: Displaying Variable
        run: echo "Hi $FullName"
