name: 17-Dynamic Variable
on: workflow_dispatch
jobs:
  dynamic_variable:
    runs-on: ubuntu-latest
    steps:
      - name: Settting Variable
        run: echo "Repository=${{ github.event.repository }}" >> $GITHUB_ENV

      - name: Displaying Variable
        run: echo "Hi $Repository"
